# Netlify configuration for War Thunder Stats Mini App
# Updated: 2024-06-28 - Static site only

[build]
  publish = "mini_app"
  command = "echo 'GameStats Mini App - No build required'"

# SPA redirects - all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Ignore Python files during build
[build.environment]
  NODE_VERSION = "18" 