services:
  - type: web
    name: warstats-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    repo: Gree1t/warstats-mini-app 